host: go.zyran.dev
repositories:
  - name: Ignis
    vsc: git
    repo: https://github.com/ZyranDev/ignis
    branch: master
    redirect: https://discord.gg/q8gh7YFN7s
  - name: Filter
    vsc: git
    repo: https://github.com/ZyranDev/filter
    branch: master
    redirect: https://discord.gg/q8gh7YFN7s
  - name: Grocery
    vsc: git
    repo: https://github.com/ZyranDev/grocery
    branch: main
    redirect: https://discord.gg/q8gh7YFN7s
